---
- name: ensure homebrew/php is tapped
  homebrew_tap: tap=homebrew/php

- name: ensure php56 is installed/updated
  homebrew: name=php56 state=latest install_options=without-pear

- name: ensure drush is installed/updated from HEAD
  homebrew: name=drush state=head
