---
- name: ensure homebrew/php is tapped
  homebrew_tap: tap=homebrew/php

- name: ensure php56 is installed/updated
  homebrew: name=php56 state=latest install_options=without-pear

- name: ensure composer is installed/updated
  homebrew: name=composer state=latest

- name: ensure composer is installed/updated
  homebrew: name=composer state=latest

- name: ensure drush is installed
  shell: composer global require drush/drush:dev-master
  register: drush_install
  changed_when: >
    'Nothing to install or update' not in drush_install.stderr

- name: ensure configuration is added to stack.d
  copy: src={{ item }} dest={{ stack_d }}
  with_items:
    - drupal.zsh

- name: ensure valkyrie is installed
  command: drush dl valkyrie
  args:
    creates: ~/.drush/valkyrie
